title: "Elliot Mitchum"
description: "A Software Engineering Journey"
url: ""
exclude: [
  .editorconfig,
  .gitignore,
  docker-compose.yml,
  Gemfile,
  Gemfile.lock,
  package.json,
  yarn.lock
]
highlighter: false
kramdown:
  auto_ids: false
