version: "2"
services:
  web:
    command: ["jekyll", "serve", "--drafts"]
    image: "jekyll/jekyll"
    volumes:
      - "./:/srv/jekyll"
    ports:
      - "4000"
  node:
    image: "ellioseven/node:9"
    volumes:
      - "./:/srv"
